# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    needs: [build] # This ensures that the 'publish' job only runs after the 'build' job has completed successfully
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --output ./build
    - name: Pack
      run: dotnet pack --no-build --configuration Release --output ./nupkg
    - name: Push
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: DropBear.Extensions.Slim/DropBear.Extensions.Slim.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
